config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :abouts

  resources :contacts

  resources :sources

  resources :intros

  resources :whats

  resources :elements

  resources :whiches

  resources :producers

  resources :animations

  resources :mains

  get 'mains/index'
  root 'mains#index'

end

app/models/about.rb
class About < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/animation.rb
class Animation < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  attr_accessible :name, :surname, :description

  validates :name, presence: true, uniqueness: true


end

app/models/element.rb
class Element < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/intro.rb
class Intro < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/producer.rb
class Producer < ActiveRecord::Base

  attr_accessible :name, :link, :description

  validates :name, presence: true, uniqueness: true

end

app/models/source.rb
class Source < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/what.rb
class What < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true


end

app/models/which.rb
class Which < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true


end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:name, :description)
    end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name, :description)
    end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
def home
end
end

app/controllers/whats_controller.rb
class WhatsController < ApplicationController
  before_action :set_what, only: [:show, :edit, :update, :destroy]

  # GET /whats
  # GET /whats.json
  def index
    @whats = What.all
  end

  # GET /whats/1
  # GET /whats/1.json
  def show
  end

  # GET /whats/new
  def new
    @what = What.new
  end

  # GET /whats/1/edit
  def edit
  end

  # POST /whats
  # POST /whats.json
  def create
    @what = What.new(what_params)

    respond_to do |format|
      if @what.save
        format.html { redirect_to @what, notice: 'What was successfully created.' }
        format.json { render :show, status: :created, location: @what }
      else
        format.html { render :new }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whats/1
  # PATCH/PUT /whats/1.json
  def update
    respond_to do |format|
      if @what.update(what_params)
        format.html { redirect_to @what, notice: 'What was successfully updated.' }
        format.json { render :show, status: :ok, location: @what }
      else
        format.html { render :edit }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whats/1
  # DELETE /whats/1.json
  def destroy
    @what.destroy
    respond_to do |format|
      format.html { redirect_to whats_url, notice: 'What was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_what
      @what = What.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def what_params
      params.require(:what).permit(:name, :description)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/intros_helper.rb
module IntrosHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/whats_helper.rb
module WhatsHelper
end

app/helpers/whiches_helper.rb
module WhichesHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing Element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<section>

<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
      
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
    		    <li>
			<%= link_to 'Poznaj CATa', intros_path %>
		    </li>
                    <li>
			<%= link_to 'O stronie', abouts_path %> 
                    </li>
                    <li>
                        <%= link_to 'Źródła', sources_path %>
                    </li>
                    <li>
                        <%= link_to 'Kontakt', contacts_path %>
                    </li>
		    <li>
                        <%= link_to 'Strona główna', mains_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">NARZĘDZIA CAT DLA POCZĄTKUJĄCYCH</h1>
                </div>
            </div>
        </div>
    </header>

	<hr>

    <div class="container">

  <tbody>
    <% @elements.each do |element| %>
      <tr>
	<div class="row">
		<div class="col-lg-12">
        <h2><td><%= element.name %></td></h2>
        <p><td><%= element.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</section>

app/views/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @element.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @element.description %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>