config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :abouts

  resources :contacts

  resources :sources

  resources :intros

  resources :whats

  resources :elements

  resources :whiches

  resources :producers

  resources :animations

  resources :mains

  get 'mains/index'
  root 'mains#index'

end

app/models/about.rb
class About < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/animation.rb
class Animation < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  attr_accessible :name, :surname, :description

  validates :name, presence: true, uniqueness: true


end

app/models/element.rb
class Element < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/intro.rb
class Intro < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/producer.rb
class Producer < ActiveRecord::Base

  attr_accessible :name, :link, :description

  validates :name, presence: true, uniqueness: true

end

app/models/source.rb
class Source < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true

end

app/models/what.rb
class What < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true


end

app/models/which.rb
class Which < ActiveRecord::Base

  attr_accessible :name, :description

  validates :name, presence: true, uniqueness: true


end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
def home
end
end

app/controllers/whats_controller.rb
class WhatsController < ApplicationController
  before_action :set_what, only: [:show, :edit, :update, :destroy]

  # GET /whats
  # GET /whats.json
  def index
    @whats = What.all
  end

  # GET /whats/1
  # GET /whats/1.json
  def show
  end

  # GET /whats/new
  def new
    @what = What.new
  end

  # GET /whats/1/edit
  def edit
  end

  # POST /whats
  # POST /whats.json
  def create
    @what = What.new(what_params)

    respond_to do |format|
      if @what.save
        format.html { redirect_to @what, notice: 'What was successfully created.' }
        format.json { render :show, status: :created, location: @what }
      else
        format.html { render :new }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whats/1
  # PATCH/PUT /whats/1.json
  def update
    respond_to do |format|
      if @what.update(what_params)
        format.html { redirect_to @what, notice: 'What was successfully updated.' }
        format.json { render :show, status: :ok, location: @what }
      else
        format.html { render :edit }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whats/1
  # DELETE /whats/1.json
  def destroy
    @what.destroy
    respond_to do |format|
      format.html { redirect_to whats_url, notice: 'What was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_what
      @what = What.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def what_params
      params.require(:what).permit(:name, :description)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/intros_helper.rb
module IntrosHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/whats_helper.rb
module WhatsHelper
end

app/helpers/whiches_helper.rb
module WhichesHelper
end

app/views/mains/index.html.erb
<body>


    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
		    <li>
			<%= link_to 'Poznaj CATa', intros_path %>
		    </li>
                    <li>
			<%= link_to 'O stronie', abouts_path %> 
                    </li>
                    <li>
                        <%= link_to 'Źródła', sources_path %>
                    </li>
                    <li>
                        <%= link_to 'Kontakt', contacts_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">NARZĘDZIA CAT DLA POCZĄTKUJĄCYCH</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr>

        <div class="row">
            <div class="col-sm-8">
                <h2>Wstęp - historia tłumaczeń</h2>
                <p>Krótka historia tłumaczeń i rozwóju narzędzi CAT oraz ich znaczenie w kulturze i biznesie.</p>
                
                <p>
                    <a class="btn btn-default btn-lg" <%= link_to 'Dowiedz się więcej', intros_path %> &raquo;</a>
                </p>
            </div>
            <div class="col-sm-4">
                <h2></h2>
                <address>
                    <strong></strong>
                    <br>
                    <br>
                    <br>
                </address>
                <address>
                    <abbr title="Phone"></abbr>
                    <br>
                    <abbr title="Email"></abbr> <a href="mailto:#"></a>
                </address>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
		<p>
		<h2>
		<%= link_to 'Co to jest CAT Tool?', whats_path %>
		</h2>
                <p><ul>
                <li>Do czego służy program
                <li>Podstawy działania
                <li>Dlaczego warto korzystać z narzędzi CAT
                </ul></p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
		<p>                
		<h2>
		<%= link_to 'Co składa się na CATa?', elements_path %>
		</h2>
                <p><ul>
                <li>Pamięć tłumaczeń (TM)
                <li>Glosariusz
		<li>QA
                </ul></p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
		<p>                
		<h2>
		<%= link_to 'Animowany tutorial', animations_path %>
		</h2>
                <p>Tutaj możecie znaleźć animowany filmik o narzędziach CAT.</p>
            </div>
        </div>
        <!-- /.row -->

        <hr>
        


        <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
		<p>                
		<h2>
		<%= link_to 'Który CAT?', whiches_path %>
		</h2>
                <p><ul>
                <li>Dostępne programy
                <li>Lista darmowych CATów
                <li>CATy webowe – tłumaczenie w przeglądarce
                </ul></p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
		<p>                
		<h2>
		<%= link_to 'Strony Producentów', producers_path %>
		</h2>
                <p>Oficjalne portale ważniejszych producentów komercyjnych i niekomercyjnych narzędzi CAT.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://wierzba.wzks.uj.edu.pl/~12_knap/seminarium/projekt/szablon/kot.png" alt="">
                <p>
		<h2>
		<%= link_to 'Przydatne strony', sources_path %>
		</h2>
                <p>Lista przydatnych portali o tematyce CAT Tools.</p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; EPI UJ 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>